Repository Night-GUA/YuAntiCheat, pull requests merged in 2024-07, with the labels that each got.

#15 修复代码中的警告导致框架报错+整理代码
  YuAntiCheat/CheatCheck/AUMCheat.cs
  YuAntiCheat/CheatCheck/AntiCheatForAll.cs
  YuAntiCheat/CheatCheck/MalumMenuCheck.cs
  YuAntiCheat/CheatCheck/SMCheat.cs
  YuAntiCheat/Keys/Keys.cs
  YuAntiCheat/Main.cs
  YuAntiCheat/Modules/Debugger.cs
  YuAntiCheat/Modules/Downloader.cs
  YuAntiCheat/Modules/RegistryManager.cs
  YuAntiCheat/Modules/Updater.cs
  YuAntiCheat/Patches/ChatBubblePatch.cs
  YuAntiCheat/Patches/CustomPopup.cs
  YuAntiCheat/Patches/FunctionPatch.cs
  YuAntiCheat/Patches/MainMenuManagerPatch.cs
  YuAntiCheat/Patches/ModManagerLateUpdatePatch.cs
  YuAntiCheat/Patches/OnPlayerJoinedPatch.cs
  YuAntiCheat/Patches/OnlyYuAntiCheat.cs
  YuAntiCheat/Patches/Ping.cs
  YuAntiCheat/Patches/PlayerPhysicPatch.cs
  YuAntiCheat/Patches/RPC.cs
  YuAntiCheat/Patches/SendInGamePatch.cs
  YuAntiCheat/Patches/UpdateFriendCodeUIPatch.cs
  YuAntiCheat/Send/SendChat.cs
  YuAntiCheat/UI/MainMenuButtonHoverAnimation.cs
  YuAntiCheat/UI/MenuUI.cs
  YuAntiCheat/UI/TitleLogoPatch.cs
  YuAntiCheat/Utils/GetPlayer.cs
  YuAntiCheat/Utils/ResourceUtils.cs
  YuAntiCheat/Utils/Utils.cs
Labels: fix bug

#19 Update Japanese.yaml
  YuAntiCheat/Resources/Languages/Japanese.yaml
Labels: Translation

#21 Update Readme.md
  Readme.md
Labels: Translation, some change
